### ISSUE TITLE
Some maps seem to generate incorrectly

### ISSUE THREAD

**Issue by monochromeandvivid** [Yasha-jin/osuLNmaster#1]
Hello. A few of the maps I made using your tool get stuck at loading screen when I am trying to play them. The game also starts consuming a lot of cpu power until I restart the game. What they all have in common is that they're made out of old maps. I assume something goes wrong when working with the old beatmap format. I haven't had any issues with newer maps so far. Problematic maps:
https://osu.ppy.sh/beatmapsets/215151#mania/521572 [7K] lZenxl's HD
https://osu.ppy.sh/beatmapsets/179951#mania/433397 [7K] Hard
https://osu.ppy.sh/beatmapsets/153316#mania/414680 7K NM+
Settings I was using: BG - 4, ML - 4, OD5 (ON), HP7 (ON), LN - ON, NSV - ON.
While at it, can you please make settings not reset every reboot? Adding a button that clears the queue would be nice too since you can only add maps and have to restart the program to make the number of ready maps zero. Thanks!

**Comment by Yasha-jin** [comment]
Fixed the issues, it was because i forgot about the [Colours] section in the files. Those map work now.
Also added your suggestion, latest version have a clear queue button as well as save your settings 👍
