### ISSUE TITLE
Two bugs

### ISSUE THREAD

**Issue by monochromeandvivid** [Yasha-jin/osuLNmaster#2]
Hi. Thank you for improving your program! After using it a bit more, I found two more bugs.
The first one is the program setting the slider velocity multiplier to 0.01 for some reason, while the map is supposed to be NSV. Link: https://osu.ppy.sh/beatmapsets/800102#mania/1679798 ([7K] Tails' ADVANCED)
The second bug: the program gets confused by the : symbol and ignores everything that goes after it as a result. For example, let's take this map https://osu.ppy.sh/beatmapsets/642457#mania/1872640. If you convert Rivals' 7K NormaL, it will mess up the name of the .osu file and some lines in the file itself: Title, TitleUnicode, Source. That's where the : was. The same thing might happen with some other symbols, I'm not sure. Please look into it. Thank you!

**Comment by Yasha-jin** [comment]
Fixed on v1.0.5
